name: "FrogBot Security Scan"
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Force Executable Permissions on Wrapper 🛠️
        run: chmod +x mvnw

      - name: Run FrogBot
        uses: jfrog/frogbot@v2
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_PROVIDER: github
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_REPOS_SELECTION_REPOS: "spring-boot-docker-libs-snapshot"
